name: 'eia_electricity_analytics'
version: '1.0.0'
config-version: 2


profile: 'eia_electricity_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  
  eia_electricity_analytics:
    
    
    staging:
      +materialized: view
      +tags: ["staging"]

    
    marts:
      +materialized: table
      +tags: ["production"]